version: '3.1'

# Test file
services:
# Server setup
  server:
    # Wait until mongo is up to make the server
    # Technically not really needed, but can avoid potential issues
    build:
      # Where to find the docker file for the server
      context: .
    # Keeping restart off; If it fails, prob should stay down
    restart: "no"
    volumes:
      # Don't overwrite this folder
      - /srv/node_modules
      # Redirect anything else in our server folder to the container
      # Note that '/srv' is the working directory in the container
      - ./:/srv
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASS=${ADMIN_PASS}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_USER=${MONGODB_USER}
      # Host should be same as IP the machine this compose is run on!
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    ports:
      # Map external port to internal port. Use environ var
      - ${SERVER_PORT}:${SERVER_PORT}